export default [
  {
    id: "iron-man",
    slug: "tony-stark",
    firstName: "Tony",
    lastName: "Stark",
    alias: "Iron Man",
    organization: "Marvel",
    powers: ["Genius Intellect", "Powered Armor Suit", "Flight"],
    description: "Genius billionaire playboy philanthropist",
  },
  {
    id: "hulk",
    slug: "bruce-banner",
    firstName: "Bruce",
    lastName: "Banner",
    alias: "The Hulk",
    organization: "Marvel",
    powers: ["Superhuman Strength", "Regeneration", "Gamma Radiation"],
    description: "Scientist transformed by gamma radiation",
  },
  {
    id: "thor",
    slug: "thor-odinson",
    firstName: "Thor",
    lastName: "Odinson",
    alias: "God of Thunder",
    organization: "Marvel",
    powers: ["Control Lightning", "Superhuman Strength", "Mjolnir"],
    description: "Asgardian god of thunder",
  },
  {
    id: "black-widow",
    slug: "natasha-romanoff",
    firstName: "Natasha",
    lastName: "Romanoff",
    alias: "Black Widow",
    organization: "Marvel",
    powers: ["Master Spy", "Expert Fighter", "Tactical Genius"],
    description: "Former Russian spy turned Avenger",
  },
  {
    id: "captain-america",
    slug: "steve-rogers",
    firstName: "Steve",
    lastName: "Rogers",
    alias: "Captain America",
    organization: "Marvel",
    powers: ["Peak Human Strength", "Master Tactician", "Vibranium Shield"],
    description: "Super-soldier and leader of the Avengers",
  },
];
